### ISSUE TITLE
vela CLI login segfaults when server is not accessible

### ISSUE THREAD

**Issue by JohnCgp** [go-vela/community#277]
## Description

Similar to #76, with `VELA_ADDR` environment variable configured, I get this when trying to login while not connected to the corporate VPN (and have no path to the vela instance):

```
> vela login
Open https://<vela URL>/ in your browser and complete authentication (Press Enter to confirm): y
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xf9830f]

goroutine 1 [running]:
github.com/go-vela/cli/action/login.(*Config).Tokens(0xc0000945f0, 0xc00043c3f0, 0xc000540500, 0x19, 0xc00000bbf0, 0x1)
        /github/workspace/action/login/login.go:98 +0x3af
github.com/go-vela/cli/action/login.(*Config).Login(0xc0000945f0, 0xc00043c3f0, 0xc000006010, 0x0)
        /github/workspace/action/login/login.go:61 +0x267
github.com/go-vela/cli/action.runLogin(0xc000091100, 0x6, 0xa)
        /github/workspace/action/login.go:117 +0x14a
github.com/urfave/cli/v2.(*Command).Run(0x2bf9da0, 0xc000090c00, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0004244e0, 0x2213490, 0xc00003a220, 0xc00007c3c0, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x825
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /github/workspace/cmd/vela-cli/main.go:128 +0xe05
```

## Value

UX is quite harsh. As #76 mentions, inaccessible endpoint should display a user-friendly message.

## Useful Information

1. What is the output of `vela --version`?

```
> vela --version
vela version v0.7.4
```

2. What operating system is being used?

Windows 10.

3. Any other important details?

Once connected to the VPN login works.

**Comment by JohnCgp** [comment]
Ah, I see this is a dupe of #266, closing.
