### ISSUE TITLE
Unsafe concurrent access to maps

### ISSUE THREAD

**Issue by wass3r** [go-vela/community#342]
## Description

Observed in pipelines with 80+ stages where many stages execute a similar workload concurrently and run for a similar amount of time. The result an be a 5000+ line stack trace on the worker. The worker crashes, restarts, and causes an abandoned build. The juicy part from the stack trace is:

```
concurrent map read and map write

goroutine 2034687 [running]:
runtime.throw(0x18dd4c5, 0x21)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000443bb8 sp=0xc000443b88 pc=0x436692
runtime.mapaccess2_faststr(0x16d2640, 0xc0053a07e0, 0xc00040fba0, 0xe, 0xc000443cd0, 0x1)
        /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc000443c28 sp=0xc000443bb8 pc=0x4141c5
github.com/go-vela/pkg-executor/executor/linux.(*client).PlanStage(0xc0030f2840, 0x1ad33e0, 0xc005101f00, 0xc0001a3c20, 0xc0053a07e0, 0x1, 0x1)
        /go/pkg/mod/github.com/go-vela/pkg-executor@v0.7.5/executor/linux/stage.go:75 +0x2b8 fp=0xc000443ec0 sp=0xc000443c28 pc=0x147d1d8
github.com/go-vela/pkg-executor/executor/linux.(*client).ExecBuild.func2(0x0, 0xc004f45a40)
        /go/pkg/mod/github.com/go-vela/pkg-executor@v0.7.5/executor/linux/build.go:452 +0x125 fp=0xc000443f78 sp=0xc000443ec0 pc=0x14811a5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0053a07b0, 0xc0053a09c0)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59 fp=0xc000443fd0 sp=0xc000443f78 pc=0xa69479
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000443fd8 sp=0xc000443fd0 pc=0x46c301
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
.
.
.
```

## Value

Worker doesn't crash and cause abandoned builds for pipelines with large amounts of stages.

## Useful Information

1. What is the output of `vela --version`?

2. What operating system is being used?

3. Any other important details?

**Comment by wass3r** [comment]
Part of the solution is probably updating:
https://github.com/go-vela/pkg-executor/blob/fc80c76ebd7cc2fddfe544ab378c81d0ed37a229/executor/linux/build.go#L431

To get a similar treatment as https://github.com/go-vela/pkg-executor/blob/v0.7.5/executor/linux/linux.go#L39-L43, ie. turn it into a `sync.Map`
