### ISSUE TITLE
Passing --template without a token causes a non-descriptive segfault

### ISSUE THREAD

**Issue by colindean** [go-vela/community#785]
## Description

I tried to run 

    vela validate pipeline --template --compiler.github.url https://git.mycompany.com

And I'm met with a segfault:

```
$ vela validate pipeline --template --compiler.github.url https://git.mycompany.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x102053cbc]

goroutine 1 [running]:
github.com/go-vela/server/compiler/native.(*client).getTemplate(0x1400022b440, 0x14000492000, {0x14000896f78, 0x6})
        /home/runner/go/pkg/mod/github.com/go-vela/server@v0.18.1/compiler/native/expand.go:210 +0x55c
github.com/go-vela/server/compiler/native.(*client).ExpandSteps(0x140001588c0?, 0x1400052f230, 0x1400052f3d0)
        /home/runner/go/pkg/mod/github.com/go-vela/server@v0.18.1/compiler/native/expand.go:93 +0x2a0
github.com/go-vela/server/compiler/native.(*client).ExpandStages(0x1025d6780?, 0x140001588c0, 0x1400052f3d0)
        /home/runner/go/pkg/mod/github.com/go-vela/server@v0.18.1/compiler/native/expand.go:33 +0x110
github.com/go-vela/server/compiler/native.(*client).CompileLite(0x1400022b440, {0x10250a3a0?, 0x1400089c430?}, 0x1, 0x0, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/go-vela/server@v0.18.1/compiler/native/compile.go:158 +0x440
github.com/go-vela/cli/action/pipeline.(*Config).ValidateLocal(0x140004c4a00, {0x10294d008, 0x1400022b440})
        /home/runner/work/cli/cli/action/pipeline/validate.go:110 +0x1d8
github.com/go-vela/cli/command/pipeline.validate(0x103922b60?)
        /home/runner/work/cli/cli/command/pipeline/validate.go:194 +0x388
github.com/urfave/cli/v2.(*Command).Run(0x103922b60, 0x14000343a40, {0x14000343ac0, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:273 +0x78c
github.com/urfave/cli/v2.(*Command).Run(0x103925760, 0x14000343640, {0x14000493540, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:266 +0x9ac
github.com/urfave/cli/v2.(*Command).Run(0x14000851e40, 0x14000342e00, {0x1400004c1e0, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/command.go:266 +0x9ac
github.com/urfave/cli/v2.(*App).RunContext(0x1400077c3c0, {0x102936b90?, 0x140000540f8}, {0x1400004c1e0, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:332 +0x604
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.24.4/app.go:309
main.main()
        /home/runner/work/cli/cli/cmd/vela-cli/main.go:139 +0x1330

```

So, when this is missing and `--template` is specified, there's a segfault if there's no token provided.

I can also trigger the failure with simply

    vela validate pipeline --template

## Value

The user can't tell what's wrong. I only know what's wrong because I accidentally deleted a parameter set in the script I am using to wrap the output: the `--compiler.github.token`.

## Useful Information

1. What is the output of `vela --version`?

```
$ vela --version
vela version v0.18.2
```

2. What operating system is being used?

```
$ sw_vers 
ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68
```

3. Any other important details?

#589 is somewhat related, although the Vela token is affected in that one.

**Comment by wass3r** [comment]
i believe this is fixed in the most recent version of the CLI. i am able to run `vela validate pipeline --template` and `vela validate pipeline --template --compiler.github.url https://git.mycompany.com`. it will complain about missing credentials for github enterprise targets. i can see an improvement on the cli side to be more specific about what someone can do to fix it however, but that's not specifically what this issue is about. feel free to reopen if you still see this.
